// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // URL utilisée par la CLI (migrate/introspect) uniquement — distincte de
  // DATABASE_URL, lu directement par lib/db.ts pour les requêtes de l'app.
  // Le pooler en mode transaction (DATABASE_URL, port 6543) ne supporte pas
  // les verrous advisory dont `prisma migrate` a besoin ; DIRECT_URL pointe
  // vers le même pooler en mode session (port 5432), qui les supporte.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
